# Generated by Django 5.1 on 2025-09-25 07:22

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="InterviewSessionSetup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("restored_at", models.DateTimeField(blank=True, null=True)),
                ("transaction_id", models.UUIDField(blank=True, null=True)),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="The date and time when this object was created.",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="The date and time when this object was last updated.",
                    ),
                ),
                (
                    "interviewer_name",
                    models.CharField(
                        default="Matthew",
                        help_text="The name of the interviewer",
                        max_length=50,
                    ),
                ),
                (
                    "model_voice",
                    models.CharField(
                        choices=[
                            ("matthew", "Matthew"),
                            ("tiffany", "Tiffany"),
                            ("amy", "Amy"),
                            ("lupe", "Lupe"),
                            ("carlos", "Carlos"),
                            ("ambre", "Ambre"),
                            ("florian", "Florian"),
                            ("greta", "Greta"),
                            ("lennart", "Lennart"),
                            ("beatrice", "Beatrice"),
                            ("lorenzo", "Lorenzo"),
                        ],
                        default="matthew",
                        help_text="The voice for the speech to speech model",
                        max_length=20,
                    ),
                ),
                (
                    "preferred_language",
                    models.CharField(
                        choices=[("English", "English"), ("Spanish", "Spanish")],
                        default="English",
                        help_text="The preferred language for the speech to speech model",
                        max_length=50,
                    ),
                ),
                (
                    "interviewer_attitude",
                    models.CharField(
                        choices=[
                            ("Friendly", "Friendly"),
                            ("Formal", "Formal"),
                            ("Challenging", "Challenging"),
                            ("Supportive", "Supportive"),
                            ("Neutral", "Neutral"),
                        ],
                        default="Friendly",
                        help_text="The attitude of the interviewer",
                        max_length=50,
                    ),
                ),
                (
                    "interview_type",
                    models.CharField(default="initial_interview", max_length=50),
                ),
            ],
            options={
                "verbose_name": "Interview Session Setup",
                "verbose_name_plural": "Interview Session Setups",
                "db_table": "interview_session_setup",
                "ordering": ["-created_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="JobProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("restored_at", models.DateTimeField(blank=True, null=True)),
                ("transaction_id", models.UUIDField(blank=True, null=True)),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="The date and time when this object was created.",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="The date and time when this object was last updated.",
                    ),
                ),
                (
                    "profile_name",
                    models.CharField(
                        help_text="A user-defined name for this profile, e.g., 'Senior Python Role at Google'.",
                        max_length=255,
                    ),
                ),
                (
                    "target_role",
                    models.CharField(
                        help_text="The job title the user is targeting, e.g., 'Senior Python Developer'.",
                        max_length=255,
                    ),
                ),
                (
                    "job_description",
                    models.TextField(
                        blank=True,
                        help_text="The full text of the job description the user is applying for.",
                    ),
                ),
                (
                    "company_name",
                    models.CharField(
                        help_text="The name of the company the user is applying",
                        max_length=50,
                    ),
                ),
                (
                    "company_background",
                    models.TextField(
                        blank=True,
                        help_text="Brief description of the company background",
                    ),
                ),
                (
                    "responsibilities",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="A list of key responsibilities for this job profile.",
                    ),
                ),
                (
                    "required_skills",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="A list of skills required for this job profile.",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="The user who owns this job profile.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="job_profiles",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Job Profile",
                "verbose_name_plural": "Job Profiles",
                "db_table": "job_profile",
                "ordering": ["-created_at"],
                "abstract": False,
                "unique_together": {("user", "profile_name")},
            },
        ),
        migrations.CreateModel(
            name="InterviewSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("restored_at", models.DateTimeField(blank=True, null=True)),
                ("transaction_id", models.UUIDField(blank=True, null=True)),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="The date and time when this object was created.",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="The date and time when this object was last updated.",
                    ),
                ),
                (
                    "prompt_name",
                    models.UUIDField(
                        default=uuid.uuid4,
                        help_text="The unique identifier for the prompt used in this session.",
                    ),
                ),
                (
                    "s2s_system_prompt",
                    models.TextField(
                        blank=True,
                        help_text="The system prompt for the speech to speech model",
                    ),
                ),
                (
                    "inference_config",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Configuration parameters for the AI models used in this session.",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("CREATED", "Created"),
                            ("IN_PROGRESS", "In Progress"),
                            ("COMPLETED", "Completed"),
                            ("INCOMPLETE", "Incomplete"),
                            ("CANCELLED", "Cancelled"),
                            ("ERROR", "Error"),
                        ],
                        default="CREATED",
                        max_length=20,
                    ),
                ),
                (
                    "session_feedback",
                    models.JSONField(
                        blank=True,
                        help_text="An AI-generated feedback of the user's performance in the session.",
                    ),
                ),
                (
                    "full_transcript",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="The full transcript of the interview session, including both user and AI responses.",
                    ),
                ),
                (
                    "session_cost",
                    models.DecimalField(
                        decimal_places=4,
                        default=0.0,
                        help_text="The cost incurred for this session based on model usage.",
                        max_digits=10,
                    ),
                ),
                (
                    "session_setup",
                    models.ForeignKey(
                        help_text="The session setup selected by the user previously",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="coaching.interviewsessionsetup",
                    ),
                ),
                (
                    "job_profile",
                    models.ForeignKey(
                        help_text="The job profile this session is for.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="interview_sessions",
                        to="coaching.jobprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Interview Session",
                "verbose_name_plural": "Interview Sessions",
                "db_table": "interview_session",
                "ordering": ["-created_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="UserResume",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("restored_at", models.DateTimeField(blank=True, null=True)),
                ("transaction_id", models.UUIDField(blank=True, null=True)),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="The date and time when this object was created.",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="The date and time when this object was last updated.",
                    ),
                ),
                (
                    "current_role",
                    models.CharField(
                        help_text="The job role currently held by the user, e.g., 'Software Engineer'.",
                        max_length=255,
                    ),
                ),
                (
                    "key_skills",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="A list of key skills, technologies, and experiences.",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="The full description text of the user's resume.",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="The user associated with this resume.",
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User Resume",
                "verbose_name_plural": "User Resumes",
                "db_table": "user_resume",
                "ordering": ["-created_at"],
                "abstract": False,
                "unique_together": {("user", "current_role")},
            },
        ),
    ]
