# Generated by Django 5.1 on 2025-09-01 13:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="JobProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("restored_at", models.DateTimeField(blank=True, null=True)),
                ("transaction_id", models.UUIDField(blank=True, null=True)),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="The date and time when this object was created.",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="The date and time when this object was last updated.",
                    ),
                ),
                (
                    "profile_name",
                    models.CharField(
                        help_text="A user-defined name for this profile, e.g., 'Senior Python Role at Google'.",
                        max_length=255,
                    ),
                ),
                (
                    "target_role",
                    models.CharField(
                        help_text="The job title the user is targeting, e.g., 'Senior Python Developer'.",
                        max_length=255,
                    ),
                ),
                (
                    "job_description_text",
                    models.TextField(
                        blank=True,
                        help_text="The full text of the job description the user is applying for.",
                    ),
                ),
                (
                    "resume_text",
                    models.TextField(
                        blank=True,
                        help_text="The full text of the user's resume, tailored for this role.",
                    ),
                ),
                (
                    "key_skills",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="A list of key skills, technologies, and experiences extracted by the AI.",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="The user who owns this job profile.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="job_profiles",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Job Profile",
                "verbose_name_plural": "Job Profiles",
                "db_table": "coaching_job_profile",
                "ordering": ["-created_at"],
                "abstract": False,
                "unique_together": {("user", "profile_name")},
            },
        ),
        migrations.CreateModel(
            name="InterviewSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("restored_at", models.DateTimeField(blank=True, null=True)),
                ("transaction_id", models.UUIDField(blank=True, null=True)),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="The date and time when this object was created.",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="The date and time when this object was last updated.",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("IN_PROGRESS", "In Progress"),
                            ("COMPLETED", "Completed"),
                            ("ERROR", "Error"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                (
                    "session_summary",
                    models.TextField(
                        blank=True,
                        help_text="An AI-generated summary of the user's performance in the session.",
                    ),
                ),
                (
                    "full_transcript",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="The full transcript of the interview, including questions, answers, and feedback.",
                    ),
                ),
                (
                    "job_profile",
                    models.ForeignKey(
                        help_text="The job profile this session is for.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="interview_sessions",
                        to="coaching.jobprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Interview Session",
                "verbose_name_plural": "Interview Sessions",
                "db_table": "coaching_interview_session",
                "ordering": ["-created_at"],
                "abstract": False,
            },
        ),
    ]
