# Generated by Django 5.1 on 2025-09-25 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("coaching", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="interviewsession",
            name="full_transcript",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="The full transcript of the interview session, including both user and AI responses.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="interviewsession",
            name="session_feedback",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="An AI-generated feedback of the user's performance in the session.",
            ),
        ),
    ]
